### ISSUE TITLE
Day 8 : persisting a new object

### ISSUE THREAD

**Issue by liloo2040** [gregurco/jobeet#2]
Hi!

It's me again!

This time, the form is displayed, except when you want to persist a new job offer.
The error says 

> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'token' cannot be null

I have checked the Job entity (token), same for token event listener, controller.

**Comment by gregurco** [comment]
Hello :slightly_smiling_face: 
Did you implement this listener https://github.com/gregurco/jobeet-tutorial/blob/master/docs/days/day-8.md#protecting-the-job-form-with-a-token ?

**Comment by liloo2040** [comment]
Yes, I did it and I removed the `->add('token')` on the JobType.

**Comment by gregurco** [comment]
@liloo2040 correct and is there still an error?

**Comment by liloo2040** [comment]
Yes, I still have the same error.

**Comment by gregurco** [comment]
@liloo2040 did you try to clear cache with command `bin/console cache:clear`. Because sometimes yaml configuration is cached and some changes are ignored.

**Comment by liloo2040** [comment]
Hi! I just tried to clear the cache with the command you just told me. It still doesn't work....

**Comment by gregurco** [comment]
@liloo2040 I installed your project I found the error :slightly_smiling_face:  Please fix the `config/services.yaml`:
```yaml
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    max_jobs_on_homepage: 10
    max_jobs_on_category: 20
    jobs_directory: '%kernel.project_dir%/public/uploads/jobs'
    jobs_web_directory: '/uploads/jobs'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%jobs_directory%'

    App\EventListener\JobUploadListener:
        tags:
        - { name: doctrine.event_listener, event: prePersist }
        - { name: doctrine.event_listener, event: preUpdate }
        - { name: doctrine.event_listener, event: postLoad }

    App\EventListener\JobTokenListener:
        tags:
        - { name: doctrine.event_listener, event: prePersist }
```

notice that all services should be defined at the end of file, after general `App\Controller\:` definition.
Also you have typo in `src/EventListener/JobUploadListener.php`:
```diff
- public function postLoad(LifecyleEventArgs $args)
+ public function postLoad(LifecycleEventArgs $args)
```

And definitely I will add this remark to guide :slightly_smiling_face:
